/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-08-27 00:03:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.co_002dbuying;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/kopo_finalProject_API/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/art-tech-manager/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1628045688839L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/myCss.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"contents-wrap\">\r\n");
      out.write("\t\t<!-- Start Banner Hero -->\r\n");
      out.write("\t    <div id=\"work_banner\" class=\"banner-wrapper bg-light w-100 py-5\">\r\n");
      out.write("\t        <div class=\"banner-vertical-center-work container text-light d-flex justify-content-center align-items-center py-5 p-0\">\r\n");
      out.write("\t            <div class=\"banner-content col-lg-8 col-12 m-lg-auto text-center\">\r\n");
      out.write("\t                <h1 class=\"banner-heading h2 display-3 pb-5 semi-bold-600 typo-space-line-center\">Our Goods</h1>\r\n");
      out.write("\t                <h3 class=\"h4 pb-2 regular-400\">Elit, sed do eiusmod tempor incididunt</h3>\r\n");
      out.write("\t                <p class=\"banner-body pb-2 light-300\">\r\n");
      out.write("\t                    Vector illustration <a class=\"text-white\" href=\"http://freepik.com/\" target=\"_blank\">Freepik</a>.\r\n");
      out.write("\t                    Lorem ipsum dolor sit amet, consectetur adipiscing elit,\r\n");
      out.write("\t                    sed do eiusmod tempor incididunt ut labore et dolore magna\r\n");
      out.write("\t                    aliqua. Quis ipsum suspendisse ultrices gravida. Risus\r\n");
      out.write("\t                    commodo viverra maecenas accumsan lacus.\r\n");
      out.write("\t                </p>\r\n");
      out.write("\t                <button type=\"button\" class=\"btn rounded-pill btn-secondary text-light px-4 light-300\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manage/goodsRegister'\" >작품 등록</button>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- End Banner Hero -->\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- Start Our Work -->\r\n");
      out.write("\t    <section class=\"container py-5\">\r\n");
      out.write("\t        <div class=\"row justify-content-center my-5\">\r\n");
      out.write("\t            <div class=\"filter-btns shadow-md rounded-pill text-center col-auto\">\r\n");
      out.write("\t                <a class=\"filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4 active\" data-filter=\".project\" href=\"#\">All</a>\r\n");
      out.write("\t                <a class=\"filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4\" data-filter=\".business\" href=\"#\">Business</a>\r\n");
      out.write("\t                <a class=\"filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4\" data-filter=\".marketing\" href=\"#\">Marketing</a>\r\n");
      out.write("\t                <a class=\"filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4\" data-filter=\".social\" href=\"#\">Social Media</a>\r\n");
      out.write("\t                <a class=\"filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4\" data-filter=\".graphic\" href=\"#\">Graphic</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t        <div class=\"row projects gx-lg-5\">\r\n");
      out.write("\t        \t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\t           \r\n");
      out.write("\t           \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        \r\n");
      out.write("\t        <div class=\"row\">\r\n");
      out.write("\t            <div class=\"btn-toolbar justify-content-center pb-4\" role=\"toolbar\" aria-label=\"Toolbar with button groups\">\r\n");
      out.write("\t                <div class=\"btn-group me-2\" role=\"group\" aria-label=\"First group\">\r\n");
      out.write("\t                    <button type=\"button\" class=\"btn btn-secondary text-white\">Previous</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"btn-group me-2\" role=\"group\" aria-label=\"Second group\">\r\n");
      out.write("\t                    <button type=\"button\" class=\"btn btn-light\">1</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"btn-group me-2\" role=\"group\" aria-label=\"Second group\">\r\n");
      out.write("\t                    <button type=\"button\" class=\"btn btn-secondary text-white\">2</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                <div class=\"btn-group\" role=\"group\" aria-label=\"Third group\">\r\n");
      out.write("\t                    <button type=\"button\" class=\"btn btn-secondary text-white\">Next</button>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </section>\r\n");
      out.write("\t    <!-- End Our Work -->\r\n");
      out.write("\t\r\n");
      out.write("\t    \r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <!-- Lightbox -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/fslightbox.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        fsLightboxInstances['gallery'].props.loadOnlyCurrentSource = true;\r\n");
      out.write("    </script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/pages/co-buying/goods.jsp(46,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/pages/co-buying/goods.jsp(46,10) '${artworkInfoList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${artworkInfoList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/pages/co-buying/goods.jsp(46,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("artworkInfo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t            <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/manage/goodsDetail/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${artworkInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"col-sm-6 col-lg-4 text-decoration-none project marketing social business\">\r\n");
            out.write("\t\t                <div class=\"service-work overflow-hidden card mb-5 mx-5 m-sm-0\">\r\n");
            out.write("\t\t                    <img class=\"card-img-top goodsImg\" src=\"/artworkImg/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${artworkInfo.artworkImg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"...\">\r\n");
            out.write("\t\t                    <div class=\"card-body\">\r\n");
            out.write("\t\t                        <h5 class=\"card-title light-300 text-dark\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${artworkInfo.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("\t\t                        <p class=\"card-text light-300 text-dark\">\r\n");
            out.write("\t\t                            ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${artworkInfo.writerName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t\t                        </p>\r\n");
            out.write("\t\t                        <span class=\"text-decoration-none text-primary light-300\">\r\n");
            out.write("\t\t                              ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${artworkInfo.stateName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" <i class='bx bxs-hand-right ms-1'></i>\r\n");
            out.write("\t\t                          </span>\r\n");
            out.write("\t\t                    </div>\r\n");
            out.write("\t\t                </div>\r\n");
            out.write("\t\t            </a>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
