/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-08-28 06:30:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lnag=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("\t    <meta charset=\"utf-8\">\r\n");
      out.write("\t    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("\t    <title>sign up</title>\r\n");
      out.write("\t    <meta name=\"description\" content=\"\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("\t    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"img/favicon.png\">\r\n");
      out.write("\t    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- CSS here -->\r\n");
      out.write("\t    \r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t    \r\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/signup.css\">\r\n");
      out.write("\t    <!-- <link rel=\"stylesheet\" href=\"css/responsive.css\"> -->\r\n");
      out.write("\t    \r\n");
      out.write("\t    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\t    <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//이름 \r\n");
      out.write("\t\t\t\t$('#name').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif($('#name').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#nameCheck').html('필수 정보입니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#nameCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t}else if(!/[a-zA-Z가-힣]/.test($('#name').val())){\r\n");
      out.write("\t\t\t\t\t\t$('#nameCheck').html('한글과 영문 대 소문자를 사용하세요. (특수기호, 공백 사용 불가).')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#nameCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t$('#nameCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#nameCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//아이디\r\n");
      out.write("\t\t\t\t$('#user_id').keyup(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($('#user_id').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#user_idCheck').html('사용할 아이디를 입력해주세요.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#user_idCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t}  else if ( !/^[a-z0-9_]{4,20}$/.test($('#user_id').val()) ) {\r\n");
      out.write("\t\t\t\t\t\t$('#user_idCheck').html('아이디는 대소문자, 숫자만 입력가능합니다.(4자리에서 20자리까지 가능)')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#user_idCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/idCheck\",\r\n");
      out.write("\t\t\t\t\t\t\tmathod : 'post',\r\n");
      out.write("\t\t\t\t\t\t\tasync: false,\r\n");
      out.write("\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\"userId\" : $('#user_id').val()\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data){ \r\n");
      out.write("\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$('#user_idCheck').empty()\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data == '0'){ //아이디 사용 가능\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#user_idCheck').html('사용가능')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.querySelector('#user_idCheck').style.color = \"#03c75a\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.querySelector('#user_idCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{ //아이디 사용 불가\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#user_idCheck').html('중복되는 아이디입니다.')\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.querySelector('#user_idCheck').style.color = \"#FF0000\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdocument.querySelector('#user_idCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//패스워드\r\n");
      out.write("\t\t\t\tlet pwMsg = document.querySelector('.user_password');\r\n");
      out.write("\t\t\t\tlet pwImg = document.querySelector('#pswd_img');\r\n");
      out.write("\t\t\t\tlet pwMsgArea = document.querySelector('.int_pass');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//패스워드\r\n");
      out.write("\t\t\t\t$('#user_password').keyup(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($('#user_password').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#user_passwordCheck').html('필수 정보입니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#user_passwordCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t} else if( !/^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,25}$/.test($('#user_password').val())) {\r\n");
      out.write("\t\t\t\t\t\t$('#user_passwordCheck').html('숫자+영문자+특수문자 조합으로 8자리 이상 사용')\r\n");
      out.write("\t\t\t\t\t\tpwMsg.innerHTML = \"사용불가\";\r\n");
      out.write("\t\t\t\t\t\tpwMsgArea.style.paddingRight = \"93px\";\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#user_passwordCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tpwMsg.style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\tpwImg.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_not_use.png\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t$('#user_passwordCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#user_passwordCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t\tpwMsg.innerHTML = \"안전\";\r\n");
      out.write("\t\t\t\t        pwMsg.style.color = \"#03c75a\";\r\n");
      out.write("\t\t\t\t        pwMsg.style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\tpwImg.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_safe.png\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet rePswd_img = document.querySelector('#rePswd_img');\r\n");
      out.write("\t\t\t\t//패스워드 확인\r\n");
      out.write("\t\t\t\t$('#user_rePassword').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif($('#user_password').val() != $('#user_rePassword').val()) {\r\n");
      out.write("\t\t\t\t\t\t$('#user_rePasswordCheck').html('비밀번호가 일치하지 않습니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#user_rePasswordCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\trePswd_img.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_check_enable.png\";\r\n");
      out.write("\t\t\t\t\t\t$('#user_rePasswordCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#user_rePasswordCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//휴대전화\r\n");
      out.write("\t\t\t\t$('#mobile').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif($('#mobile').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#mobileCheck').html('핸드폰 번호를 입력하세요.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#mobileCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t}else if( !/([01]{2})([01679]{1})([0-9]{3,4})([0-9]{4})/.test($('#mobile').val()) ) {\r\n");
      out.write("\t\t\t\t\t\t$('#mobileCheck').html('형식에 맞지 않는 번호입니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#mobileCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t$('#mobileCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#mobileCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet phoneAuthNum = ''\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//핸드폰 인증 클릭\r\n");
      out.write("\t\t\t\t$('#smsAuth').click(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth/smsAuth\",\r\n");
      out.write("\t\t\t\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"phone\" : $('#mobile').val()\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tphoneAuthNum = data\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(data)\r\n");
      out.write("\t\t\t\t\t\t\t$('#mobileCheck').html('문자가 전송되었습니다 인증번호를 입력하세요.')\r\n");
      out.write("\t\t\t\t\t\t\tdocument.querySelector('#mobileCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function (request, status, error){\r\n");
      out.write("\t\t\t\t\t\t\tvar msg = \"ERROR : \" + request.status + \"<br>\"\r\n");
      out.write("\t\t\t\t\t\t\tmsg += + \"내용 : \" + request.responseText + \"<br>\" + error;\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(msg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//핸드폰 인증번호 입력\r\n");
      out.write("\t\t\t\t$('#mobileNo').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif(phoneAuthNum == '') {\r\n");
      out.write("\t\t\t\t\t\t$('#mobileNoCheck').html('인증하기 버튼을 클릭해주세요.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#mobileNoCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else if(phoneAuthNum == $('#mobileNo').val() ) {\r\n");
      out.write("\t\t\t\t\t\t$('#mobileNoCheck').html('인증성공')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#mobileNoCheck').style.color = \"#03c75a\";\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#mobileNoCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$('#mobileNoCheck').html('인증번호가 잘못 입력되었습니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#mobileNoCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//주민번호\r\n");
      out.write("\t\t\t\t$('#jumin_no').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif($('#jumin_no').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#jumin_noCheck').html('필수 정보입니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#jumin_noCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else if(!/[0-9]{13}$/.test($('#jumin_no').val())){\r\n");
      out.write("\t\t\t\t\t\t$('#jumin_noCheck').html('형식에 맞지 않습니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#jumin_noCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t$('#jumin_noCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#jumin_noCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//이메일\r\n");
      out.write("\t\t\t\t$('#email').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif($('#email').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#emailCheck').html('이메일을 입력하세요.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#emailCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t}else if( !/^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i.test($('#email').val()) ) {\r\n");
      out.write("\t\t\t\t\t\t$('#emailCheck').html('형식에 맞지 않습니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#emailCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t$('#emailCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#emailCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet emailAuthNum = '';\r\n");
      out.write("\t\t\t\t//이메일 인증 클릭\r\n");
      out.write("\t\t\t\t$('#emailAuth').click(function(){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/auth/emailAuth\",\r\n");
      out.write("\t\t\t\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"email\" : $('#email').val()\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tdataType: \"text\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(data)\r\n");
      out.write("\t\t\t\t\t        emailAuthNum = data\r\n");
      out.write("\t\t\t\t\t        $('#emailCheck').html('문자가 전송되었습니다 인증번호를 입력하세요.')\r\n");
      out.write("\t\t\t\t\t\t\tdocument.querySelector('#emailCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\terror: function (request, status, error){\r\n");
      out.write("\t\t\t\t\t\t\tvar msg = \"ERROR : \" + request.status + \"<br>\"\r\n");
      out.write("\t\t\t\t\t\t\tmsg += + \"내용 : \" + request.responseText + \"<br>\" + error;\r\n");
      out.write("\t\t\t\t\t\t\tconsole.log(msg);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//이메일 인증번호 입력\r\n");
      out.write("\t\t\t\t$('#emailNo').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif(emailAuthNum == '') {\r\n");
      out.write("\t\t\t\t\t\t$('#emailNoCheck').html('인증하기 버튼을 클릭해주세요.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#emailNoCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else if(emailAuthNum == $('#emailNo').val() ) {\r\n");
      out.write("\t\t\t\t\t\t$('#emailNoCheck').html('인증성공')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#emailNoCheck').style.color = \"#03c75a\";\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#emailNoCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$('#emailNoCheck').html('인증번호가 잘못 입력되었습니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#emailNoCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//간편비밀번호\r\n");
      out.write("\t\t\t\tlet pwMsg1 = document.querySelector('.easy_password');\r\n");
      out.write("\t\t\t\tlet pwImg1 = document.querySelector('#pswd1_img1');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//간편비밀번호\r\n");
      out.write("\t\t\t\t$('#easy_password').keyup(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($('#easy_password').val() == \"\") {\r\n");
      out.write("\t\t\t\t\t\t$('#easy_passwordCheck').html('필수 정보입니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#easy_passwordCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else if( !/[0-9]{6}$/.test($('#easy_password').val())) {\r\n");
      out.write("\t\t\t\t\t\t$('#easy_passwordCheck').html('6자리 숫자만 가능합니다.')\r\n");
      out.write("\t\t\t\t\t\tpwMsg1.innerHTML = \"사용불가\";\r\n");
      out.write("\t\t\t\t\t\tpwMsgArea.style.paddingRight = \"93px\";\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#easy_passwordCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tpwMsg1.style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\tpwImg1.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_not_use.png\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t$('#easy_passwordCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#easy_passwordCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t\tpwMsg1.innerHTML = \"안전\";\r\n");
      out.write("\t\t\t\t        pwMsg1.style.color = \"#03c75a\";\r\n");
      out.write("\t\t\t\t        pwMsg1.style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t\tpwImg1.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_safe.png\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlet pwImg2 = document.querySelector('#pswd2_img1');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//간편비밀번호 확인\r\n");
      out.write("\t\t\t\t$('#reEasy_password').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif($('#easy_password').val() != $('#reEasy_password').val()) {\r\n");
      out.write("\t\t\t\t\t\t$('#reEasy_passwordCheck').html('비밀번호가 일치하지 않습니다.')\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#reEasy_passwordCheck').style.display = \"block\";\r\n");
      out.write("\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\tpwImg2.src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_check_enable.png\";\r\n");
      out.write("\t\t\t\t\t\t$('#reEasy_passwordCheck').empty()\r\n");
      out.write("\t\t\t\t\t\tdocument.querySelector('#reEasy_passwordCheck').style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})//document ready\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("    <body>\r\n");
      out.write("        \r\n");
      out.write("        <!-- wrapper -->\r\n");
      out.write("        <div id=\"wrapper\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("            <!-- content-->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("            \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/signup\" onsubmit=\"return signUpFormCheck()\" method=\"post\"> \r\n");
      out.write("            \t<input type=\"hidden\" name=\"kakao_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kakao_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t\t<h2 align=\"center\">sign up</h2>\r\n");
      out.write("            \t\t\r\n");
      out.write("\t\t\t\t\t<!-- NAME -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"name\">이름</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_name\">\r\n");
      out.write("\t                        <input type=\"text\" id=\"name\" name=\"name\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"nameCheck\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- id -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"name\">ID</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_name\">\r\n");
      out.write("\t                        <input type=\"text\" id=\"user_id\" name=\"userId\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"user_idCheck\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 패스워드 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"pswd1\">비밀번호</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_pass\">\r\n");
      out.write("\t                        <input type=\"password\" id=\"user_password\" name=\"password\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("\t                        <span id=\"alertTxt\" class=\"user_password\">사용불가</span>\r\n");
      out.write("\t                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_pass.png\" id=\"pswd_img\" class=\"pswdImg\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"user_passwordCheck\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 패스워드 확인 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"pswd2\">비밀번호 확인</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_pass_check\">\r\n");
      out.write("\t                        <input type=\"password\" id=\"user_rePassword\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("\t                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_check_disable.png\" id=\"rePswd_img\" class=\"pswdImg\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"user_rePasswordCheck\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 모바일 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"addr\">휴대전화(- 제외)</label></h3>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"bir_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"int\" id=\"mobile\" name=\"phone\" placeholder=\"전화번호 입력\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"error_next_box\" id=\"mobileCheck\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"bir_mm\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"int\" id=\"smsAuth\" value=\"전화번호 인증\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 모바일 인증번호 입력창 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"addr\">휴대전화 인증번호 입력</label></h3>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"bir_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"int\" id=\"mobileNo\"  placeholder=\"인증번호 입력\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"error_next_box\" id=\"mobileNoCheck\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"bir_mm\">\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 주민번호 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"name\">주민등록번호</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_name\">\r\n");
      out.write("\t                        <input type=\"password\" id=\"jumin_no\" name=\"juminNo\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"jumin_noCheck\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 이메일 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"addr\">이메일</label></h3>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"bir_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"int\" id=\"email\" name=\"email\" placeholder=\"이메일 입력\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"error_next_box\" id=\"emailCheck\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"bir_mm\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"int\" id=\"emailAuth\"  value=\"이메일 인증\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 이메일 인증번호 입력창 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"addr\">이메일 인증번호 입력</label></h3>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"bir_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"int\" id=\"emailNo\"  placeholder=\"인증번호 입력\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"error_next_box\" id=\"emailNoCheck\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"bir_mm\">\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                \r\n");
      out.write("\t                <!-- 간편 비밀번호 -->\r\n");
      out.write("\t                <!-- PW1 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"pswd1\">간편 비밀번호(6자리)</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_pass\">\r\n");
      out.write("\t                        <input type=\"password\" id=\"easy_password\" name=\"easyPassword\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("\t                        <span id=\"alertTxt\" class=\"easy_password\">사용불가</span>\r\n");
      out.write("\t                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_pass.png\" id=\"pswd1_img1\" class=\"pswdImg\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"easy_passwordCheck\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\r\n");
      out.write("\t                <!-- PW2 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"pswd2\">간편 비밀번호 재확인 (6자리)</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_pass_check\">\r\n");
      out.write("\t                        <input type=\"password\" id=\"reEasy_password\" class=\"int\" maxlength=\"20\">\r\n");
      out.write("\t                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/signup/m_icon_check_disable.png\" id=\"pswd2_img1\" class=\"pswdImg\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"reEasy_passwordCheck\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t                \r\n");
      out.write("\t\r\n");
      out.write("\t                <!-- BIRTH -->\r\n");
      out.write("\t                \r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"yy\">생년월일</label></h3>\r\n");
      out.write("\t                    <span class=\"box int_bir\">\r\n");
      out.write("\t                    \t<input type=\"date\" id=\"birth\" name=\"birth\" class=\"int\" maxlength=\"16\" required=\"required\">\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\" id=\"birthCheck\"></span>\r\n");
      out.write("\t                    \r\n");
      out.write("\t                </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t\r\n");
      out.write("\t                <!-- GENDER -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"gender\">성별</label></h3>\r\n");
      out.write("\t                    <span class=\"gender_code\">\r\n");
      out.write("\t                        <select id=\"gender\" class=\"sel\" name=\"gender\" required=\"required\">\r\n");
      out.write("\t                            <option>선택</option>\r\n");
      out.write("\t                            <option value=\"M\">남자</option>\r\n");
      out.write("\t                            <option value=\"F\">여자</option>\r\n");
      out.write("\t                        </select>                            \r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- addr -->\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 우편주소 -->\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"join_title\"><label for=\"addr\">우편번호</label></h3>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"bir_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"int\" name=\"zipcode\" id=\"sample4_postcode\" placeholder=\"우편번호 찾기를 눌러주세요.\" required=\"required\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"error_next_box\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"bir_mm\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"int\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 도로명 주소 -->\r\n");
      out.write("\t\t                <div>\r\n");
      out.write("\t\t                    <h3 class=\"join_title\"><label for=\"name\">도로명 주소</label></h3>\r\n");
      out.write("\t\t                    <span class=\"box int_name\">\r\n");
      out.write("\t\t                        <input type=\"text\" class=\"int\" name=\"addr1Load\" id=\"sample4_roadAddress\" placeholder=\"우편번호 찾기를 눌러주세요.\" required=\"required\" readonly>\r\n");
      out.write("\t\t                    </span>\r\n");
      out.write("\t\t                    <span class=\"error_next_box\"></span>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                <!-- 지번 주소 -->\r\n");
      out.write("\t\t                <div>\r\n");
      out.write("\t\t                    <h3 class=\"join_title\"><label for=\"name\">지번 주소</label></h3>\r\n");
      out.write("\t\t                    <span class=\"box int_name\">\r\n");
      out.write("\t\t                        <input type=\"text\" class=\"int\" name=\"addr1Jibun\" id=\"sample4_jibunAddress\" placeholder=\"우편번호 찾기를 눌러주세요.\" required=\"required\" readonly>\r\n");
      out.write("\t\t                    </span>\r\n");
      out.write("\t\t                    <span id=\"guide\" style=\"color:#999;display:none\"></span>\r\n");
      out.write("\t\t                    <span class=\"error_next_box\"></span>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                <!-- 상세 주소 -->\r\n");
      out.write("\t\t                <div>\r\n");
      out.write("\t\t                    <h3 class=\"join_title\"><label for=\"name\">상세주소</label></h3>\r\n");
      out.write("\t\t                    <span class=\"box int_name\">\r\n");
      out.write("\t\t                    \t<input type=\"text\" class=\"int\" name=\"addr2\" id=\"sample4_detailAddress\" placeholder=\"상세주소\" required=\"required\">\r\n");
      out.write("\t\t                    </span>\r\n");
      out.write("\t\t                    <span class=\"error_next_box\"></span>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<!-- 카카오 알림 받을건지 -->\r\n");
      out.write("\t                <div>\r\n");
      out.write("\t                    <h3 class=\"join_title\"><label for=\"name\">카카오톡 알림을 받으시겠습니까?<br>(회원가입 후 마이페이지에서 카카오 연동을 진행하셔야 합니다.)</label></h3>\r\n");
      out.write("\t                    <span>\r\n");
      out.write("\t                    \t<input type=\"radio\" id=\"receive_sms_yn\" name=\"receiveKakaoYn\" value=\"Y\" > <label for=\"name\">수신</label>\r\n");
      out.write("\t                    \t<input type=\"radio\" id=\"receive_sms_yn\" name=\"receiveKakaoYn\" value=\"N\"> <label for=\"name\">수신 거부</label>\r\n");
      out.write("\t                    </span>\r\n");
      out.write("\t                    <span class=\"error_next_box\"></span>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t               \r\n");
      out.write("\t\r\n");
      out.write("\t                <!-- JOIN BTN-->\r\n");
      out.write("\t                <div class=\"btn_area\">\r\n");
      out.write("\t                \t<input type=\"submit\" id=\"btnJoin\" value=\"join\">\r\n");
      out.write("\t                </div>\r\n");
      out.write("\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div> \r\n");
      out.write("            <!-- content-->\r\n");
      out.write("\r\n");
      out.write("        </div> \r\n");
      out.write("        <!-- wrapper -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/signUp.js\"></script>\r\n");
      out.write("    <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t    function sample4_execDaumPostcode() {\r\n");
      out.write("\t        new daum.Postcode({\r\n");
      out.write("\t            oncomplete: function(data) {\r\n");
      out.write("\t                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\t\r\n");
      out.write("\t                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("\t                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t                var roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t                var extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\t\r\n");
      out.write("\t                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("\t                    extraRoadAddr += data.bname;\r\n");
      out.write("\t                }\r\n");
      out.write("\t                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("\t                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("\t                }\r\n");
      out.write("\t                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t                if(extraRoadAddr !== ''){\r\n");
      out.write("\t                    extraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t                }\r\n");
      out.write("\t\r\n");
      out.write("\t                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t                document.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("\t                document.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("\t                document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("\t                \r\n");
      out.write("\t\r\n");
      out.write("\t                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("\t                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("\t                if(data.autoRoadAddress) {\r\n");
      out.write("\t                    var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("\t                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("\t                    guideTextBox.style.display = 'block';\r\n");
      out.write("\t\r\n");
      out.write("\t                } else if(data.autoJibunAddress) {\r\n");
      out.write("\t                    var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("\t                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("\t                    guideTextBox.style.display = 'block';\r\n");
      out.write("\t                } else {\r\n");
      out.write("\t                    guideTextBox.innerHTML = '';\r\n");
      out.write("\t                    guideTextBox.style.display = 'none';\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }).open();\r\n");
      out.write("\t    }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
