/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-08-27 00:00:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Start Banner Hero -->\r\n");
      out.write("    <div class=\"banner-wrapper bg-light\">\r\n");
      out.write("        <div id=\"index_banner\" class=\"banner-vertical-center-index container-fluid pt-5\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Start slider -->\r\n");
      out.write("            <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("                <ol class=\"carousel-indicators\">\r\n");
      out.write("                    <li data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                    <li data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("                    <li data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <div class=\"carousel-inner\">\r\n");
      out.write("                    <div class=\"carousel-item active\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"py-5 row d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"banner-content col-lg-8 col-8 offset-2 m-lg-auto text-left py-5 pb-5\">\r\n");
      out.write("                                <h1 class=\"banner-heading h1 text-secondary display-3 mb-0 pb-5 mx-0 px-0 light-300 typo-space-line\">\r\n");
      out.write("                                    Develop <strong>Strategies</strong> for \r\n");
      out.write("                                  <br>your business\r\n");
      out.write("                              </h1>\r\n");
      out.write("                                <p class=\"banner-body text-muted py-3 mx-0 px-0\">\r\n");
      out.write("                                    Purple Buzz is a corporate HTML template with Bootstrap 5 Beta 1. This CSS template is 100% free to download provided by <a rel=\"nofollow\" href=\"https://templatemo.com/page/1\" target=\"_parent\">TemplateMo</a>. Total 6 HTML pages included in this template. Icon fonts by <a rel=\"nofollow\" href=\"https://boxicons.com/\" target=\"_blank\">Boxicons</a>. Photos are from <a rel=\"nofollow\" href=\"https://unsplash.com/\" target=\"_blank\">Unsplash</a> and <a rel=\"nofollow\" href=\"https://icons8.com/\" target=\"_blank\">Icons 8</a>.\r\n");
      out.write("                              </p>\r\n");
      out.write("                                <a class=\"banner-button btn rounded-pill btn-outline-primary btn-lg px-4\" href=\"#\" role=\"button\">Get Started</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"carousel-item\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"py-5 row d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"banner-content col-lg-8 col-8 offset-2 m-lg-auto text-left py-5 pb-5\">\r\n");
      out.write("                                <h1 class=\"banner-heading h1 text-secondary display-3 mb-0 pb-3 mx-0 px-0 light-300\">\r\n");
      out.write("                                    HTML CSS Template with Bootstrap 5 Beta 1\r\n");
      out.write("                                </h1>\r\n");
      out.write("                                <p class=\"banner-body text-muted py-3\">\r\n");
      out.write("                                    You are not allowed to re-distribute this Purple Buzz HTML template as a downloadable ZIP file on any kind of Free CSS collection websites. This is strongly prohibited. Please contact TemplateMo for more information.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <a class=\"banner-button btn rounded-pill btn-outline-primary btn-lg px-4\" href=\"#\" role=\"button\">Get Started</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"carousel-item\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"py-5 row d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"banner-content col-lg-8 col-8 offset-2 m-lg-auto text-left py-5 pb-5\">\r\n");
      out.write("                                <h1 class=\"banner-heading h1 text-secondary display-3 mb-0 pb-3 mx-0 px-0 light-300\">\r\n");
      out.write("                                    Cupidatat non proident, sunt in culpa qui officia\r\n");
      out.write("                                </h1>\r\n");
      out.write("                                <p class=\"banner-body text-muted py-3\">\r\n");
      out.write("                                    Ut enim ad minim veniam, quis nostrud exercitation ullamco\r\n");
      out.write("                                    laboris nisi ut aliquip ex ea commodo consequat. Duis aute\r\n");
      out.write("                                    irure dolor in reprehenderit in voluptate velit esse cillum\r\n");
      out.write("                                    dolore eu fugiat nulla pariatur. Excepteur sint occaecat.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <a class=\"banner-button btn rounded-pill btn-outline-primary btn-lg px-4\" href=\"#\" role=\"button\">Get Started</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a class=\"carousel-control-prev text-decoration-none\" href=\"#carouselExampleIndicators\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("                    <i class='bx bx-chevron-left'></i>\r\n");
      out.write("                    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"carousel-control-next text-decoration-none\" href=\"#carouselExampleIndicators\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("                    <i class='bx bx-chevron-right'></i>\r\n");
      out.write("                    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End slider -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Banner Hero -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Service -->\r\n");
      out.write("    <section class=\"service-wrapper py-3\">\r\n");
      out.write("        <div class=\"container-fluid pb-3\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <h2 class=\"h2 text-center col-12 py-5 semi-bold-600\">Services</h2>\r\n");
      out.write("                <div class=\"service-header col-2 col-lg-3 text-end light-300\">\r\n");
      out.write("                    <i class='bx bx-gift h3 mt-1'></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"service-heading col-10 col-lg-9 text-start float-end light-300\">\r\n");
      out.write("                    <h2 class=\"h3 pb-4 typo-space-line\">Make Success for future</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"service-footer col-10 offset-2 col-lg-9 offset-lg-3 text-start pb-3 text-muted px-2\">\r\n");
      out.write("                You are free to use this template for your commercial or business websites. You are not allowed to re-distribute this template ZIP file on any template collection websites. It is too easy to illegally copy and repost this template.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"service-tag py-5 bg-secondary\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <ul class=\"nav d-flex justify-content-center\">\r\n");
      out.write("                    <li class=\"nav-item mx-lg-4\">\r\n");
      out.write("                        <a class=\"filter-btn nav-link btn-outline-primary active shadow rounded-pill text-light px-4 light-300\" href=\"#\" data-filter=\".project\">All</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mx-lg-4\">\r\n");
      out.write("                        <a class=\"filter-btn nav-link btn-outline-primary rounded-pill text-light px-4 light-300\" href=\"#\" data-filter=\".graphic\">Graphics</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"filter-btn nav-item mx-lg-4\">\r\n");
      out.write("                        <a class=\"filter-btn nav-link btn-outline-primary rounded-pill text-light px-4 light-300\" href=\"#\" data-filter=\".ui\">UI/UX</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item mx-lg-4\">\r\n");
      out.write("                        <a class=\"filter-btn nav-link btn-outline-primary rounded-pill text-light px-4 light-300\" href=\"#\" data-filter=\".branding\">Branding</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"container overflow-hidden py-5\">\r\n");
      out.write("        <div class=\"row gx-5 gx-sm-3 gx-lg-5 gy-lg-5 gy-3 pb-3 projects\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project ui branding\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"service card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-01.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">UI/UX design</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project ui graphic\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-02.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">Social Media</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project branding\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-03.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">Marketing</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project ui graphic\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-04.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">Graphic</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project ui graphic\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-05.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">Digtal Marketing</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project branding\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-06.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">Market Research</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project branding\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-07.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">Business</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Start Recent Work -->\r\n");
      out.write("            <div class=\"col-xl-3 col-md-4 col-sm-6 project ui graphic branding\">\r\n");
      out.write("                <a href=\"#\" class=\"service-work card border-0 text-white shadow-sm overflow-hidden mx-5 m-sm-0\">\r\n");
      out.write("                    <img class=\"card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/services-08.jpg\" alt=\"Card image\">\r\n");
      out.write("                    <div class=\"service-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                        <div class=\"service-work-content text-left text-light\">\r\n");
      out.write("                            <span class=\"btn btn-outline-light rounded-pill mb-lg-3 px-lg-4 light-300\">Branding</span>\r\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- End Service -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start View Work -->\r\n");
      out.write("    <section class=\"bg-secondary\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row d-flex justify-content-center text-center\">\r\n");
      out.write("                <div class=\"col-lg-2 col-12 text-light align-items-center\">\r\n");
      out.write("                    <i class='display-1 bx bxs-box bx-lg'></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-7 col-12 text-light pt-2\">\r\n");
      out.write("                    <h3 class=\"h4 light-300\">Great transformations successful</h3>\r\n");
      out.write("                    <p class=\"light-300\">Quis ipsum suspendisse ultrices gravida.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-12 pt-4\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary rounded-pill btn-block shadow px-4 py-2\">View Our Work</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- End View Work -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start Recent Work -->\r\n");
      out.write("    <section class=\"py-5 mb-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"recent-work-header row text-center pb-5\">\r\n");
      out.write("                <h2 class=\"col-md-6 m-auto h2 semi-bold-600 py-5\">Recent Works</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gy-5 g-lg-5 mb-4\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Recent Work -->\r\n");
      out.write("                <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"recent-work card border-0 shadow-lg overflow-hidden\">\r\n");
      out.write("                        <img class=\"recent-work-img card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/recent-work-01.jpg\" alt=\"Card image\">\r\n");
      out.write("                        <div class=\"recent-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                            <div class=\"recent-work-content text-start mb-3 ml-3 text-dark\">\r\n");
      out.write("                                <h3 class=\"card-title light-300\">Social Media</h3>\r\n");
      out.write("                                <p class=\"card-text\">Ullamco laboris nisi ut aliquip ex</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Recent Work -->\r\n");
      out.write("                <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"recent-work card border-0 shadow-lg overflow-hidden\">\r\n");
      out.write("                        <img class=\"recent-work-img card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/recent-work-02.jpg\" alt=\"Card image\">\r\n");
      out.write("                        <div class=\"recent-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                            <div class=\"recent-work-content text-start mb-3 ml-3 text-dark\">\r\n");
      out.write("                                <h3 class=\"card-title light-300\">Web Marketing</h3>\r\n");
      out.write("                                <p class=\"card-text\">Psum officia anim id est laborum.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Recent Work -->\r\n");
      out.write("                <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"recent-work card border-0 shadow-lg overflow-hidden\">\r\n");
      out.write("                        <img class=\"recent-work-img card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/recent-work-03.jpg\" alt=\"Card image\">\r\n");
      out.write("                        <div class=\"recent-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                            <div class=\"recent-work-content text-start mb-3 ml-3 text-dark\">\r\n");
      out.write("                                <h3 class=\"card-title light-300\">R & D</h3>\r\n");
      out.write("                                <p class=\"card-text\">Sum dolor sit consencutur</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Recent Work -->\r\n");
      out.write("                <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"recent-work card border-0 shadow-lg overflow-hidden\">\r\n");
      out.write("                        <img class=\"recent-work-img card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/recent-work-04.jpg\" alt=\"Card image\">\r\n");
      out.write("                        <div class=\"recent-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                            <div class=\"recent-work-content text-start mb-3 ml-3 text-dark\">\r\n");
      out.write("                                <h3 class=\"card-title light-300\">Public Relation</h3>\r\n");
      out.write("                                <p class=\"card-text\">Lorem ipsum dolor sit amet</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Recent Work -->\r\n");
      out.write("                <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"recent-work card border-0 shadow-lg overflow-hidden\">\r\n");
      out.write("                        <img class=\"recent-work-img card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/recent-work-05.jpg\" alt=\"Card image\">\r\n");
      out.write("                        <div class=\"recent-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                            <div class=\"recent-work-content text-start mb-3 ml-3 text-dark\">\r\n");
      out.write("                                <h3 class=\"card-title light-300\">Branding</h3>\r\n");
      out.write("                                <p class=\"card-text\">Put enim ad minim veniam</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Recent Work -->\r\n");
      out.write("                <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                    <a href=\"#\" class=\"recent-work card border-0 shadow-lg overflow-hidden\">\r\n");
      out.write("                        <img class=\"recent-work-img card-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/recent-work-06.jpg\" alt=\"Card image\">\r\n");
      out.write("                        <div class=\"recent-work-vertical card-img-overlay d-flex align-items-end\">\r\n");
      out.write("                            <div class=\"recent-work-content text-start mb-3 ml-3 text-dark\">\r\n");
      out.write("                                <h3 class=\"card-title light-300\">Creative Design</h3>\r\n");
      out.write("                                <p class=\"card-text\">Mollit anim id est laborum.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div><!-- End Recent Work -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- End Recent Work -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
