/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2021-08-26 16:50:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.8.jar", Long.valueOf(1628045705101L));
    _jspx_dependants.put("jar:file:/C:/kopo_finalProject_API/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/art-tech/WEB-INF/lib/tiles-jsp-3.0.8.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1506773284000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Transportion</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/favicon.png\">\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/myModal.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/board/bootstrap.css\">\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("    \t$(document).ready(function(){\r\n");
      out.write("    \t\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultJoin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == 'success') {\r\n");
      out.write("    \t\t\t$('#index_content_p').text('회원가입에 성공하셨습니다.')\r\n");
      out.write("    \t\t\t$('.index_modal').css('display','block')\r\n");
      out.write("    \t\t\t$('body').css(\"overflow\", \"hidden\");\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//모달 다시 숨기기\r\n");
      out.write("    \t\t$('.index_modal_cancel').click(function(){\r\n");
      out.write("    \t\t\t$('.index_modal').css('display','none')\r\n");
      out.write("    \t\t\t$('body').css(\"overflow\", \"scroll\");\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t})\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!--[if lte IE 9]>\r\n");
      out.write("            <p class=\"browserupgrade\">You are using an <strong>outdated</strong> browser. Please <a href=\"https://browsehappy.com/\">upgrade your browser</a> to improve your experience and security.</p>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    <!-- slider_area_start -->\r\n");
      out.write("    <div class=\"slider_area\">\r\n");
      out.write("        <div class=\"single_slider  d-flex align-items-center slider_bg_1\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-8\">\r\n");
      out.write("                        <div class=\"slider_text text-center justify-content-center\">\r\n");
      out.write("                            <p>For Personal & Business</p>\r\n");
      out.write("                            <h3>Global Logistic Service\r\n");
      out.write("                                For Business</h3>\r\n");
      out.write("                                <a class=\"boxed-btn3\" href=\"service.html\">Our Services</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- slider_area_end -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- service_area start -->\r\n");
      out.write("    <div class=\"service_area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-12\">\r\n");
      out.write("                    <div class=\"section_title mb-50 text-center\">\r\n");
      out.write("                        <h3>\r\n");
      out.write("                            Art work\r\n");
      out.write("                        </h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-12\">\r\n");
      out.write("                    <div class=\"service_active owl-carousel\">\r\n");
      out.write("                        <div class=\"single_service\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service_info\">\r\n");
      out.write("                                <h3><a href=\"service_details.html\">작품명</a></h3>\r\n");
      out.write("                                <p>로이 리히텐슈타인 Roy Lichtenstein</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 25%; background-color: #191970\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                            <p> 0 / 4462 조각 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_service\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service_info\">\r\n");
      out.write("                                <h3><a href=\"service_details.html\">작품명</a></h3>\r\n");
      out.write("                                <p>로이 리히텐슈타인 Roy Lichtenstein</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 25%; background-color: #191970\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                            <p> 0 / 4462 조각 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_service\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service_info\">\r\n");
      out.write("                                <h3><a href=\"service_details.html\">작품명</a></h3>\r\n");
      out.write("                                <p>로이 리히텐슈타인 Roy Lichtenstein</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 25%; background-color: #191970\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                            <p> 0 / 4462 조각 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_service\">\r\n");
      out.write("                            <div class=\"thumb\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"service_info\">\r\n");
      out.write("                                <h3><a href=\"service_details.html\">작품명</a></h3>\r\n");
      out.write("                                <p>로이 리히텐슈타인 Roy Lichtenstein</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 25%; background-color: #191970\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("                            <p> 0 / 4462 조각 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- service_area end -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- recommend_goods -->\r\n");
      out.write("\t<div class=\"recommend_goods_contain\">\r\n");
      out.write("\t\t<div class=\"recommendGoods_main\">\r\n");
      out.write("\t  \t\t<p class=\"recommendGoods_main_title\">이런 작품은 어떤가요?</p>\r\n");
      out.write("\t  \t\t<p>나와 비슷한 투자성향을 가진 사용자들이 고른 작품</p>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t        <div class=\"row\">\r\n");
      out.write("\t        \t<!-- 하나  -->\r\n");
      out.write("\t            <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("\t                <div class=\"single_service\">\r\n");
      out.write("\t                    <div class=\"thumb\">\r\n");
      out.write("\t                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"service_info\">\r\n");
      out.write("\t                        <h3><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/co-buying/goodsDetail\">Still Life with Picasso from Hom</a></h3>\r\n");
      out.write("\t                        <p>로이 리히텐슈타인 Roy Lichtenstein</p>\r\n");
      out.write("\t                        \r\n");
      out.write("\t                        <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 25%; background-color: #191970\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t                        <p> 0 / 4462 조각 </p>\r\n");
      out.write("\t                   \t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- 하나 끝  -->\r\n");
      out.write("\t            \r\n");
      out.write("\t            <!-- 하나  -->\r\n");
      out.write("\t            <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("\t                <div class=\"single_service\">\r\n");
      out.write("\t                    <div class=\"thumb\">\r\n");
      out.write("\t                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"service_info\">\r\n");
      out.write("\t                        <h3><a href=\"service_details.html\">Still Life with Picasso from Hom</a></h3>\r\n");
      out.write("\t                        <p>로이 리히텐슈타인 Roy Lichtenstein</p>\r\n");
      out.write("\t                        \r\n");
      out.write("\t                        <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 25%; background-color: #191970\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t                        <p> 0 / 4462 조각 </p>\r\n");
      out.write("\t                   \t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- 하나 끝  -->\r\n");
      out.write("\t            \r\n");
      out.write("\t            <!-- 하나  -->\r\n");
      out.write("\t            <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("\t                <div class=\"single_service\">\r\n");
      out.write("\t                    <div class=\"thumb\">\r\n");
      out.write("\t                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"service_info\">\r\n");
      out.write("\t                        <h3><a href=\"service_details.html\">Still Life with Picasso from Hom</a></h3>\r\n");
      out.write("\t                        <p>로이 리히텐슈타인 Roy Lichtenstein</p>\r\n");
      out.write("\t                        \r\n");
      out.write("\t                        <div class=\"progress\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"progress-bar\" role=\"progressbar\" style=\"width: 25%; background-color: #191970\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t                        <p> 0 / 4462 조각 </p>\r\n");
      out.write("\t                   \t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <!-- 하나 끝  -->\r\n");
      out.write("\t            \r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<!-- recommend_goods end -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <!-- counter_area  -->\r\n");
      out.write("    <div class=\"counter_area\">\r\n");
      out.write("      \t<div class=\"section_title mb-50 text-center\">\r\n");
      out.write("             <h3>\r\n");
      out.write("                1023일 동안 <br> 누적 거래현황\r\n");
      out.write("             </h3>\r\n");
      out.write("             <p>2021.08.01 기준</p>\r\n");
      out.write("         </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"offcan_bg\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-3\">\r\n");
      out.write("                        <div class=\"single_counter text-center\">\r\n");
      out.write("                            <h3> <span class=\"counter\">42</span> <span>+</span> </h3>\r\n");
      out.write("                            <p>총 판매금액</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-3\">\r\n");
      out.write("                        <div class=\"single_counter text-center\">\r\n");
      out.write("                            <h3> <span class=\"counter\">97</span> <span>+</span> </h3>\r\n");
      out.write("                            <p>총 모집 작품 수</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-3\">\r\n");
      out.write("                        <div class=\"single_counter text-center\">\r\n");
      out.write("                            <h3> <span class=\"counter\">2342</span></h3>\r\n");
      out.write("                            <p>총 판매 조각 수</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-3\">\r\n");
      out.write("                        <div class=\"single_counter text-center\">\r\n");
      out.write("                            <h3> <span class=\"counter\">42</span> <span>+</span> </h3>\r\n");
      out.write("                            <p>총 매각 작품 수</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-3\">\r\n");
      out.write("                        <div class=\"single_counter text-center\">\r\n");
      out.write("                            <h3> <span class=\"counter\">97</span> <span>+</span> </h3>\r\n");
      out.write("                            <p>매각 평균 수익률</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-4 col-md-3\">\r\n");
      out.write("                        <div class=\"single_counter text-center\">\r\n");
      out.write("                            <h3> <span class=\"counter\">2342</span></h3>\r\n");
      out.write("                            <p>연환산 평균 수익률</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /counter_area  -->\r\n");
      out.write("    \r\n");
      out.write("\t<!-- testimonial_area  -->\r\n");
      out.write("    <div class=\"testimonial_area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-7\">\r\n");
      out.write("                    <div class=\"testmonial_active owl-carousel\">\r\n");
      out.write("                        <div class=\"single_carousel\">\r\n");
      out.write("                            <div class=\"single_testmonial text-center\">\r\n");
      out.write("                            \t<div>\r\n");
      out.write("                            \t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/about/counter.png\">\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single_carousel\">\r\n");
      out.write("                            <div class=\"single_testmonial text-center\">\r\n");
      out.write("                            \t<div>\r\n");
      out.write("                            \t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/about/counter.png\">\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"single_carousel\">\r\n");
      out.write("                            <div class=\"single_testmonial text-center\">\r\n");
      out.write("                            \t<div>\r\n");
      out.write("                            \t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/about/counter.png\">\r\n");
      out.write("                            \t</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xl-5\">\r\n");
      out.write("\t\t                <div class=\"single_carousel\">\r\n");
      out.write("\t\t                \t<div class=\"single_testmonial text-center\">\r\n");
      out.write("\t\t\t                \t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead >\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t<th >공지사항 </th>\r\n");
      out.write("\t\t\t\t\t\t\t\t    \t<td class=\"testimonial_area_td\"><a href=\"#\" >전체보기</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t    </thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <tr class=\"alert\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <td colspan=\"2\">앤디 워홀 <$ (Quadrant)> 100조각 이상 구매시 엽서형 권리증 증정 이벤트</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <tr class=\"alert\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <td colspan=\"2\">앤디 워홀 <$ (Quadrant)> 100조각 이상 구매시 엽서형 권리증 증정 이벤트</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <tr class=\"alert\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <td colspan=\"2\">앤디 워홀 <$ (Quadrant)> 100조각 이상 구매시 엽서형 권리증 증정 이벤트</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <tr class=\"alert\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <td colspan=\"2\">앤디 워홀 <$ (Quadrant)> 100조각 이상 구매시 엽서형 권리증 증정 이벤트</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <tr class=\"alert\" role=\"alert\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        <td colspan=\"2\">앤디 워홀 <$ (Quadrant)> 100조각 이상 구매시 엽서형 권리증 증정 이벤트</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t                </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /testimonial_area  -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- service_area  -->\r\n");
      out.write("    <div class=\"service_area\">\r\n");
      out.write("    \t<div class=\"section_title mb-50 text-center\">\r\n");
      out.write("             <h3>\r\n");
      out.write("                 A.T 미디어\r\n");
      out.write("             </h3>\r\n");
      out.write("             <p>더보기 +<p> \r\n");
      out.write("         </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"single_service\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service_info\">\r\n");
      out.write("                            <p><a href=\"service_details.html\">기사 제목 작성하기</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"single_service\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service_info\">\r\n");
      out.write("                            <p><a href=\"service_details.html\">기사 제목 작성하기</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("                    <div class=\"single_service\">\r\n");
      out.write("                        <div class=\"thumb\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/img/service/1.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"service_info\">\r\n");
      out.write("                            <p><a href=\"service_details.html\">기사 제목 작성하기</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <!--/ service_area  -->\r\n");
      out.write("    \r\n");
      out.write("\t<!-- 모달 -->\r\n");
      out.write("\t<div class=\"index_modal\">\r\n");
      out.write("\t\t<div class=\"index_body\" >  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t<p id=\"index_content_p\"></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<div class=\"select\">\r\n");
      out.write("\t\t\t\t<p class=\"index_modal_cancel\">확인</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
